# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# PROTECTEDMEM covers cpuapp_boot_partition + periphconf_partition.
# These areas must be protected by IronSide SE so corruption is
# detected and the areas are recovered if necessary.
#
# UICR.SNAPSHOT user region: same contiguous span (boot + periphconf only).

CONFIG_GEN_UICR_PROTECTEDMEM=y


# cpuapp_boot_partition (64 KB) + periphconf_partition (8 KB) = 72 KB
CONFIG_GEN_UICR_PROTECTEDMEM_SIZE_BYTES=851968

# Physical: mram1x 0x0E000000 + offset 0x30000 = 0x0E030000, length 72 KB.
# cpuapp_boot_partition and periphconf_partition
CONFIG_GEN_UICR_SNAPSHOT_REGIONS=y
CONFIG_GEN_UICR_SNAPSHOT_REGION_0=y
CONFIG_GEN_UICR_SNAPSHOT_REGION_0_ADDRESS=0x0E030000
CONFIG_GEN_UICR_SNAPSHOT_REGION_0_SIZE_BYTES=73728

# secure_storage_partition
CONFIG_GEN_UICR_SNAPSHOT_REGION_1=y
CONFIG_GEN_UICR_SNAPSHOT_REGION_1_ADDRESS=0x0E1fd000
CONFIG_GEN_UICR_SNAPSHOT_REGION_1_SIZE_BYTES=12288

# Dummy "filesystem" placed after "cpuapp_boot_partition and
# periphconf_partition" that the sample's main() function reads
# possibly magnetically corrupted data-at-rest from
CONFIG_GEN_UICR_SNAPSHOT_REGION_2=y
CONFIG_GEN_UICR_SNAPSHOT_REGION_2_ADDRESS=0x0E042000
CONFIG_GEN_UICR_SNAPSHOT_REGION_2_SIZE_BYTES=1048576

# Dummy "filesystem" placed after "cpuapp_boot_partition and
# periphconf_partition" that the sample's main() function reads
# possibly magnetically corrupted data-at-rest from
CONFIG_GEN_UICR_SNAPSHOT_REGION_3=y
CONFIG_GEN_UICR_SNAPSHOT_REGION_3_ADDRESS=0x0E0F2000
CONFIG_GEN_UICR_SNAPSHOT_REGION_3_SIZE_BYTES=1048576

